repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
    -   id: pycln
        args: [--config=2024/py/pyproject.toml]
-   repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
    -   id: isort
        files: "2024/py/*\\.(py)$"
        args: [--settings-path=2024/py/pyproject.toml]
